---
sources:
    - name: meter_source
      interval: 600
      meters:
          - "*"
      sinks:
          - meter_sink
    - name: cpu_source
      interval: 1
      meters:
          - "cpu"
      sinks:
          - cpu_sink_fast
    - name: vm_source
      interval: 1
      meters:
          - "memory.total"
          - "memory.unused"
          - "memory.cached"
          - "memory.swap"
          - "memory.buffer"
          - "disk.usage"
      sinks:
          - meter_sink_fast
    - name: snmp_source
      interval: 1
      meters:
          - "hardware.memory.total"
          - "hardware.memory.used"
          - "hardware.cpu.load.1min"
          - "hardware.cpu.load.5min"
          - "hardware.cpu.load.15min"
          - "hardware.disk.size.total"
          - "hardware.disk.size.used"
      sinks:
          - meter_sink_fast
    - name: disk_source
      interval: 600
      meters:
          - "disk.read.bytes"
          - "disk.read.requests"
          - "disk.write.bytes"
          - "disk.write.requests"
      sinks:
          - disk_sink
    - name: network_source
      interval: 1
      meters:
          - "network.incoming.bytes"
          - "network.incoming.packets"
          - "network.outgoing.bytes"
          - "network.outgoing.packets"
          - "hardware.network.incoming.bytes"
          - "hardware.network.outgoing.bytes"
      sinks:
          - network_sink_fast
sinks:
    - name: meter_sink
      transformers:
      publishers:
          - rpc://
    - name: meter_sink_fast
      transformers:
      publishers:
          - udp://
    - name: cpu_sink
      transformers:
          - name: "rate_of_change"
            parameters:
                target:
                    name: "cpu_util"
                    unit: "%"
                    type: "gauge"
                    scale: "100.0 / (10**9 * (resource_metadata.cpu_number or 1))"
      publishers:
          - rpc://
    - name: cpu_sink_fast
      transformers:
          - name: "rate_of_change"
            parameters:
                target:
                    name: "cpu_util"
                    unit: "%"
                    type: "gauge"
                    scale: "100.0 / (10**9 * (resource_metadata.cpu_number or 1))"
      publishers:
          - udp://
    - name: disk_sink
      transformers:
          - name: "rate_of_change"
            parameters:
                source:
                    map_from:
                        name: "disk\\.(read|write)\\.(bytes|requests)"
                        unit: "(B|request)"
                target:
                    map_to:
                        name: "disk.\\1.\\2.rate"
                        unit: "\\1/s"
                    type: "gauge"
      publishers:
          - rpc://
    - name: network_sink
      transformers:
          - name: "rate_of_change"
            parameters:
                source:
                   map_from:
                       name: "network\\.(incoming|outgoing)\\.(bytes|packets)"
                       unit: "(B|packet)"
                target:
                    map_to:
                        name: "network.\\1.\\2.rate"
                        unit: "\\1/s"
                    type: "gauge"
      publishers:
          - rpc://
    - name: network_sink_fast
      transformers:
          - name: "rate_of_change"
            parameters:
                source:
                   map_from:
                       name: "network\\.(incoming|outgoing)\\.(bytes|packets)"
                       unit: "(B|packet)"
                target:
                    map_to:
                        name: "network.\\1.\\2.rate"
                        unit: "\\1/s"
                    type: "gauge"
      publishers:
          - udp://
